global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
scrape_configs:
  - job_name: 'flash-app'
    static_configs:
      - targets: ['backend:5000']